version: '3.8'
services:
  server:
    image: grpc-example-server 
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - 50051:50051
    restart: on-failure
  client:
    image: grpc-example-client
    build:
      context: client
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - server
    environment:
      - GRPC_SERVER=server:50051
      - CALL=1000
      - GODEBUG=http2debug=2