apiVersion: v1
kind: Service
metadata:
  labels:
    app: server
  name: server
  annotations:
    konghq.com/protocols: grpc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 50051
  selector:
    app: server
  type: ClusterIP